---
framework: mocha
postmerge:
  pattern:
    - "./test/*.js"
    - "./test/acceptance/*.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
premerge:
  - "./test/*.js"
  - "./test/acceptance/*.js"
prerun:
  - npm i
postrun:
  - node --version
  - echo "Ba Dum TAS... -_-"
stability:
  consecutive_runs: 5
version: 2.0
