---
framework: mocha
postMerge:
  pattern:
    - "./test/*.js"
    - "./test/acceptance/*.js"
preMerge:
  pattern:
    - "./test/*.js"
    - "./test/acceptance/*.js"
preRun:
  - npm i
postRun:
  - node --version
version: 2.0
